### ISSUE TITLE
byte swap should not be unconditional

### ISSUE THREAD

**Issue by tedu** [dchest/bcrypt_pbkdf#1]
Not sure what Go's status is on bigendian machines, but the byte swapping should only be done for little endian systems. Something like a sparc will be incorrect with the swapping.

**Comment by dchest** [comment]
Are you sure? This would mean that bcrypt-pbkdf2 gives different results on different architectures. The confusion probably is because Blowfish (and its Go package) encodes result as big endian, while `bcrypt_hash` from your C implementation changes this to little-endian:

```
    /* copy out */
    for (i = 0; i < BCRYPT_BLOCKS; i++) {
        out[4 * i + 3] = (cdata[i] >> 24) & 0xff;
        out[4 * i + 2] = (cdata[i] >> 16) & 0xff;
        out[4 * i + 1] = (cdata[i] >> 8) & 0xff;
        out[4 * i + 0] = cdata[i] & 0xff;
    }
```

What I do is, after receiving big-endian bytes from Go's `blowfish.Encrypt`, I swap them to match your implementation.

Perhaps, I should write a better comment for that part.

**Comment by tedu** [comment]
Ah, I think you're right. I was confused by what the C code was doing (which I copied from bcrypt.c). At first glance I thought it was only swapping sometimes, but I think that's because blf_enc is not a normal encryption function.
